-- Q1. What is the total shipment value generated by the company?

SELECT
    ROUND(SUM(shipment_value_usd), 2) AS total_shipment_value
FROM shipments;

-- Q2. Which customers generated the highest shipment value?

SELECT
    customer_id,
    ROUND(SUM(shipment_value_usd), 2) AS total_revenue
FROM shipments
GROUP BY customer_id
ORDER BY total_revenue DESC
LIMIT 10;

-- Q3. Which carriers generated the highest shipment value?

SELECT
    carrier_name,
    ROUND(SUM(shipment_value_usd), 2) AS total_revenue
FROM shipments
GROUP BY carrier_name
ORDER BY total_revenue DESC;

-- Q4. What is the total delay penalty charged across all shipments?

SELECT
    ROUND(SUM(total_delay_penalty_usd), 2) AS total_delay_penalty
FROM shipments;

-- Q5. Which shipment had the highest shipment value?

SELECT
    shipment_id,
    customer_id,
    carrier_name,
    shipment_value_usd
FROM shipments
ORDER BY shipment_value_usd DESC
LIMIT 1;

